### ISSUE TITLE
Should I Use This Package?

### ISSUE THREAD

**Issue by RehanSaeed** [dotnet/reproducible-builds#18]
I've followed [this post](https://devblogs.microsoft.com/dotnet/producing-packages-with-source-link/) a year or more ago to add source link like so:

```xml
  <PropertyGroup Label="Build">
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>

  <PropertyGroup Label="Source Link">
    <!-- Optional: Declare that the Repository URL can be published to NuSpec -->
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <!-- Optional: Embed source files that are not tracked by the source control manager to the PDB -->
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <!-- Optional: Include PDB in the built .nupkg -->
    <AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>
  </PropertyGroup>

  <ItemGroup Label="Package References">
    <PackageReference Include="Microsoft.SourceLink.GitHub" PrivateAssets="All" Version="1.1.1" />
  </ItemGroup>
```

I also use Cake build to set the `ContinuousIntegrationBuild` variable based on `!BuildSystem.IsLocalBuild`.

I'm trying to understand if I should switch over to `DotNet.ReproducibleBuilds`. There seem to be two differences:

1. The package sets `DebugType` to `embedded` which I believe would stop generating a snupkg file. I don't currently set `DebugType`, so the default must be coming from `SymbolPackageFormat` above. Why was embedded chosen as the default?
2. Do the source link packages also set `AllowedOutputExtensionsInPackageBuildOutputFolder`? https://github.com/ctaggart/SourceLink/pull/291 makes it pretty unclear.

**Comment by baronfel** [comment]
Embedded is _much_ simpler distribution-wise than a separate snupkg - it does increase DLL size a bit but for many customers (especially smaller OSS projects) it is a more sane default (in my opinion).  You can of course override it to use whatever DebugType your prefer.

The [SourceLink packages](https://github.com/dotnet/sourcelink) don't set `AllowedOutputExtensionsInPackageBuildOutputFolder`, because those packages don't express an opinion on the matter of _where_ the PDBs should go, only what SourceLink content should be written to them.
